// Central icon set for AssetFlow.
//
// We use Iconoir — a clean, thin-line, premium icon set that suits the
// quiet-luxury aesthetic — re-exported under the friendly names the app already
// uses, so swapping the icon library only ever touches this one file.

export {
  WarningTriangle as AlertTriangle,
  ArrowLeft,
  DataTransferBoth as ArrowLeftRight,
  ArrowRight,
  Prohibition as Ban,
  Bell,
  Packages as Boxes,
  Building as Building2,
  Calendar as CalendarClock,
  Check,
  DoubleCheck as CheckCheck,
  CheckCircle as CheckCircle2,
  NavArrowDown as ChevronDown,
  ClipboardCheck,
  Copy,
  ViewGrid as LayoutDashboard,
  ReportColumns as BarChart3,
  Download,
  DragHandGesture as GripVertical,
  InfoCircle as Info,
  Lock,
  LogOut,
  Mail as MailCheck,
  Menu,
  Box as PackageCheck,
  BoxIso as PackageOpen,
  Attachment as Paperclip,
  Plus,
  Search,
  ShieldAlert,
  ShieldCheck,
  GraphUp as TrendingUp,
  Undo as Undo2,
  Upload,
  UserCircle as UserCog,
  Wrench,
  Xmark as X,
  XmarkCircle as XCircle,
} from "iconoir-react";
